version: '3.7'
services:
  app:
    container_name: avalith-hotelo
    image: avalith_hotelo-img:1.0.0
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://kerno-postgres:5432/avalith_hotelo
    ports:
      - 8080:8080
    networks:
      kerno-network:
        ipv4_address: 172.19.0.10
networks:
  kerno-network:
    external: true
